### ISSUE TITLE
PB_16 Voltage Regulator

### ISSUE THREAD

**Issue by libby2cm** [computergeek1507/PB_16#1]
Hi, it looks like at one point this board used a buck converter, but now uses a LM7805.  Is that on purpose, or were there issues with the buck?  If the 7805 is right, does it need a heatsink or anything?

**Comment by computergeek1507** [comment]
You should use a OKI-78SR-5 buck converter. The Kicad 3D renders show a 7805 because I have not made a 3D model for the OKI-78SR-5 buck converter. The BOM also has a  OKI-78SR-5 buck converter.

**Comment by libby2cm** [comment]
Ah, got it.. missed it in BOM.  Just sending boards out to fab, so wanted to double check.. thanks!

**Comment by libby2cm** [comment]
Just a heads up, looks like it's in digikey library now, with 3d model (horizontal & vertical)

![image](https://user-images.githubusercontent.com/6451331/84959705-e087c580-b0cd-11ea-8a3f-6973f0610ec6.png)

**Comment by computergeek1507** [comment]
Do I also see the polifuse 3d model as well in your screenshot?

**Comment by libby2cm** [comment]
> Do I also see the polifuse 3d model as well in your screenshot?

Yes, I didn't change anything from your last commit though, so new version of kicad must have included new libraries/models.
