### ISSUE TITLE
Diff Expansion v4 sock has wrong pinout

### ISSUE THREAD

**Issue by fone626** [computergeek1507/PB_16#13]
Unfortunately I found this out the hard way.  The +5V and GND on the Diff_Expansion are reversed on pins 1,2 and 3,4 from what is on the BBB-16, 3to4_Adapter and the 16_Expansion.   I'm assuming the BBB-16, 3to4_Adapter and 16_Expansion have the correct pinout as that's what appears to be correct based on what little I can see from pictures of the falcon v4 expansion boards.

While researching this I also noticed the GND and +5V are reversed on the Four_Out Expansion.

**Comment by computergeek1507** [comment]
fixed I think
