### ISSUE TITLE
BBB16 Expansion

### ISSUE THREAD

**Issue by Strawberry1997** [computergeek1507/PB_16#16]
While testing the outputs I noticed that port 3, 11, 12, 16, 34, doesn't have any pixel data. I've tried it on 3 different BBB16 expansion controllers to rule out any soldering issues.
test was using BBB16 expansion > Diff Expansion > Receiver_Out_SMD > pixels strands.

Also tested the BBB16 expansion > 16_expansion SMD,  some ports work fine, some no data, some flickering.

**Comment by computergeek1507** [comment]
What eeprom file did you use?

**Comment by Strawberry1997** [comment]
I haven't used any eeprom file.Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Scott Hanson ***@***.***> Date: 4/15/22  10:16 PM  (GMT-05:00) To: computergeek1507/PB_16 ***@***.***> Cc: Strawberry1997 ***@***.***>, Author ***@***.***> Subject: Re: [computergeek1507/PB_16] BBB16 Expansion (Issue #16) 
What eeprom file did you use?

**Comment by Strawberry1997** [comment]
I've tried the BBB16 and BBB16v2 eeprom files with no JOY. seems this board needs it's unique file.

**Comment by computergeek1507** [comment]
I haven't generator one for it yet, I'll try to do it tonight.

**Comment by computergeek1507** [comment]
Unzip this file and try this eeprom

[BBB16-Exp-eeprom.zip](https://github.com/computergeek1507/PB_16/files/8502943/BBB16-Exp-eeprom.zip)

**Comment by Strawberry1997** [comment]
I've uploaded eeprom, it didn't seem too help.
Which controller> Vendor > model > variant, should I be using in Xlights?

**Comment by Strawberry1997** [comment]
The EEPROM did allow for 48 stings in multiple configurations.
The buttons for the oled control seem to not function. I'm not sure how to configure them in the gpio section.
The voltage is reading vin1 27.2v and vin2 23.9. I'm only sending 5v from a dedicated PS.

**Comment by computergeek1507** [comment]
there is no ADC circuits, I will have to fix that

**Comment by Strawberry1997** [comment]
Have you had a chance to look at the ADA circuits? is this the cause of the flicker on the 16 expansion SMD board?
