### ISSUE TITLE
Parts issue? BBB_16_SMD

### ISSUE THREAD

**Issue by Crezzie** [computergeek1507/PB_16#19]
Hi im building a cart in digi-key to have a go at building my own BBB 16. Im having trouble with one item on your list being "not found" on their website. In the BBB_16_BOM file part no 29 Digi-key reference: 2571-CN34J330CTTR-ND is the only one i cant find are you able to help or update the part number? Im in australia if this helps.

Regards luke

**Comment by Strawberry1997** [comment]
I think you have the wrong part #. I don't see this part in the BOM file. It appears you are looking for the 33 ohm resistor network.

**Comment by mrpburke** [comment]
> 

It's in the BBB 16 SMD BOM. The LCSC part # that's in the BOM is available in JLCPCB and appears to be the one you want (0603WAF330JT5E).

**Comment by Crezzie** [comment]
beautiful found it guys thanks a bunch. also 1 more thing is there an alternative to the part on line 34 Part number for digi-key 811-2196-5-ND. the lead time is crazy and literally out of stock EVERYWHERE its the dc dc 5v converter. 1 site i went to said 52 week lead time.

**Comment by mrpburke** [comment]
> beautiful found it guys thanks a bunch. also 1 more thing is there an alternative to the part on line 34 Part number for digi-key 811-2196-5-ND. the lead time is crazy and literally out of stock EVERYWHERE its the dc dc 5v converter. 1 site i went to said 52 week lead time.

I believe 102-P7805-2000-S-ND will also work.

**Comment by computergeek1507** [comment]
The regulars have been out of stock since 2020, I have been working on a design with a built-in switcher chip, but they can be hit and miss as well.
