### ISSUE TITLE
BBB_16_SMD U5 Part error

### ISSUE THREAD

**Issue by processor83** [computergeek1507/PB_16#34]
Just to let you know that this part is not correctly connected.

for users dont order this without changes!

**Comment by processor83** [comment]
Also just saw that OLED footprint should not be there in gerber files i understand its there for 3D rendering!

**Comment by bcarriveau** [comment]
Not correctly connected in what way, orientation, trace not connected, routed wrong?

**Comment by processor83** [comment]
footprint has changed and traces are not connected.  also OLED mounting holes should be removed im working on it to fix those but im not very goof with github to ask a pull of those fixes

**Comment by processor83** [comment]
![image](https://user-images.githubusercontent.com/35543827/180473769-5e565152-37b6-4619-b45f-5339fde1a7a9.png)
here is the oled part

**Comment by processor83** [comment]
and here is the U5 part 
![image](https://user-images.githubusercontent.com/35543827/180473935-8491142a-2f5c-4d50-abad-7fe29d3f684e.png)

**Comment by computergeek1507** [comment]
Ill fix it, I was consolidating libraries and might have broke it

**Comment by processor83** [comment]
Thank you!

I now also see the bleaglebone silk is showed  but im sure you will see it also!

**Comment by computergeek1507** [comment]
This should be fixed now
