### ISSUE TITLE
BBB 16 SMD V2.1 Part Placement

### ISSUE THREAD

**Issue by brymitch56** [computergeek1507/PB_16#40]
When I upload the gerber, BOM and placement files to JLCPCB, many of the through hole parts are not placed correctly. Maybe this isn't an issue, as I've read that they don't do through hole anyway. Picture of their render attached with the components circled that look wrong to me.
![BBB16 SMD Part Placement](https://user-images.githubusercontent.com/38402076/211565314-bb279a51-bd0a-46da-8de9-637979357853.PNG)

**Comment by bcarriveau** [comment]
Select the option to have jlc review it on the board selection options page and they will just adjust it for you.

**Comment by computergeek1507** [comment]
They started placing through hole components sometime in 2021. They are "extended parts" and cost an extra dollar per component part number. The JLC part placer GUI was updated last year and now most the rotation values are different. I haven't spent the time updating them all. You can manually adjust the rotation in the POS file or using the JLC plugin in KiCad.

**Comment by brymitch56** [comment]
I have never used KiCad. To generate the placement file, do I start from the gerber file, or something else? I'm willing to learn and get it fixed, but I don't know where to start.

**Comment by brymitch56** [comment]
After playing around with the layout render, I figured out you can rotate and reposition parts within the GUI before adding to your cart. Though it's a bit of a pain, it looks like it should work. I've also found the same issue with the Receiver_Out_SMD, and I expect most other SMD boards.
