### ISSUE TITLE
Receiver_Out_SMD assembly BOM incorrect RJ45

### ISSUE THREAD

**Issue by brymitch56** [computergeek1507/PB_16#41]
When trying to add the Receiver_Out_SMD to my order on JLCPCB, I noticed the RJ45 connector in the BOM only has 6 of 8 pins populated. Looking at the schematic, I assume this won't work, since it looks like all 8 pins are used. The Digi-Key and manufacturer numbers look fine in the main BOM, but the BOM within the assembly folder has LCSC part number C305972, as compared to the assembly BOM of the BBB 16 SMD that I'm also trying to order which uses part number C2938579

**Comment by computergeek1507** [comment]
fixed BOM
